FROM debian:stable-slim

ENV DEBIAN_FRONTEND=noninteractive \
    OSMO_BUILD_IN_CONTAINER=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential pkg-config git autoconf automake libtool \
      python3 python3-minimal \
  libtalloc-dev libpcsclite-dev libusb-1.0-0-dev \
      libgnutls28-dev libmnl-dev libsctp-dev systemd-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["/bin/bash","-lc","./build.sh platform=linux target=all"]
